version: '3.9'
services:
  db:
    image: postgres:14.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/db-v0.0.1:/var/lib/postgresql/data

  turbo:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/docket
      NODE_ENV: development
    volumes:
      - ./:/app/
      - /app/node_modules/
    depends_on:
      - db
