version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: dev.db.Dockerfile
    shm_size: '512m'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/db-v0.0.1:/var/lib/postgresql/data

  turbo:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app/
      - /app/node_modules/
    depends_on:
      - db
